services:
  - type: worker
    name: ff-bot
    env: python
    buildCommand: pip install -r goofish_parser/requirements.txt
    startCommand: cd goofish_parser && python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_USER_ID
        sync: false
      - key: KRW_TO_RUB
        value: "0.060"
